[package]
org = "admin"
name = "compile_time_student_data_analysis"
version = "0.1.0"
distribution = "2201.13.0-m3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name="ai.np"
version = "0.4.2"
repository="local"
